### ISSUE TITLE
createUDPClient missing

### ISSUE THREAD

**Issue by yanzixiang** [lwahlmeier/python-litesockets#1]
hi there, can u add some support to UDP ?

**Comment by lwahlmeier** [comment]
There is support for UDP, but its a little odd due to UDP being connectionless.  Basically you have to make a udpServer, and there is a createUDPClient(host,port) on that object  One UDPServer can have many clients, and if the udpServer gets a packet from a ip/port that does not already have a client the acceptClient is calledback with one.  If a client already exist it will call the reader call back on the udpClient.

**Comment by yanzixiang** [comment]
so if I want to connect to an  remote UDPServer(which is not an PC),
I must create an local UDPServer, then createUDPClient(host,port),
then i use the UDPClient to send packet to the remote UDPSever ?

**Comment by lwahlmeier** [comment]
yes, so you can create a "random" udpServer, with udpServer = se.createUDPServer("0.0.0.0", 0), this gives it a random port and binds to all interfaces, from there you can create a UDPClient, say to a google stun server to do a stun request by doing udpClient = udpServer.createUDPClient("stun.l.google.com", 19302).  From there any write called on the updClient will go to stun.l.google.com:19302 and any packets from that ip will be done on the udpClient reader callback.  If a packet from another ip/port comes in on the udpServer it will do the acceptor callback giving you another udpclient that talks to only that ip/port pair.

**Comment by yanzixiang** [comment]
hi,have you test this code in python3 ?
i use this code in python2, it runs perfectly, can read the udp packet,
but when i use the same code in python3, i can NOT　read the udp packet.
